# This rule is not used by the project gcs-storage-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over infra.colinbruner.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gcs-storage-controller
    app.kubernetes.io/managed-by: kustomize
  name: storageretention-admin-role
rules:
- apiGroups:
  - infra.colinbruner.com
  resources:
  - storageretentions
  verbs:
  - '*'
- apiGroups:
  - infra.colinbruner.com
  resources:
  - storageretentions/status
  verbs:
  - get
